apiVersion: v1
kind: Service
metadata:
  name: weather
  labels:
    run: weather 
spec:
  type: NodePort     # service type
  ports:
  - nodePort: 31200  # outter port
    port: 8080       # service port
    targetPort: 8000   # container port (pod port)
    protocol: TCP
  selector:
    app: weather 
  type: LoadBalancer
  externalIPs:
  - 43.201.246.91
