/* tslint:disable */
// This file is generated
// Do not edit this file

import type * as text from "./text";
export * as text from "./text";
import type * as markdown from "./markdown";
export * as markdown from "./markdown";
import type * as image from "./image";
export * as image from "./image";
import type * as audio from "./audio";
export * as audio from "./audio";
import type * as video from "./video";
export * as video from "./video";
import type * as file from "./file";
export * as file from "./file";
import type * as location from "./location";
export * as location from "./location";
import type * as carousel from "./carousel";
export * as carousel from "./carousel";
import type * as card from "./card";
export * as card from "./card";
import type * as dropdown from "./dropdown";
export * as dropdown from "./dropdown";
import type * as choice from "./choice";
export * as choice from "./choice";

export type ChannelChannel = {
  text: text.Text;
  markdown: markdown.Markdown;
  image: image.Image;
  audio: audio.Audio;
  video: video.Video;
  file: file.File;
  location: location.Location;
  carousel: carousel.Carousel;
  card: card.Card;
  dropdown: dropdown.Dropdown;
  choice: choice.Choice;
}
