/* tslint:disable */
// This file is generated
// Do not edit this file

import * as sdk from "@botpress/sdk";

import type * as configuration from "./configuration";
import type * as actions from "./actions/index";
import type * as channels from "./channels/index";
import type * as events from "./events/index";
export * as configuration from "./configuration";
export * as actions from "./actions/index";
export * as channels from "./channels/index";
export * as events from "./events/index";

export class Integration
      extends sdk.Integration<configuration.Configuration, actions.Actions, channels.Channels, events.Events> {}
export type IntegrationProps = sdk.IntegrationProps<configuration.Configuration, actions.Actions, channels.Channels, events.Events>;
