---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris
  namespace: default
  labels:
    app: tetris
spec:
  selector:
    matchLabels:
      app: tetris
  replicas: 1
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
        - name: tetris
          image: uzyexe/tetris
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tetris
  namespace: default
  labels:
    svc: tetris
spec:
  type: NodePort
  ports:
    - port: 80
      name: function1
      targetPort: 80
      protocol: TCP
      nodePort: 32000
  selector:
    app: tetris
  type: LoadBalancer
  externalIPs:
    - 3.34.121.69
