#Base Images
FROM ubuntu:latest

#RUN Command
RUN echo Hello~ It is a shell type command.
RUN ["echo", "Hello~ It is exec type command."]
RUN ["/bin/bash", "-c","echo 'Hello~ It is /bin/bash execution in shell type command.'"]

