/* tslint:disable */
// This file is generated
// Do not edit this file

import type * as group from "./group/index";
export * as group from "./group/index";

export type Channels = {
  group: group.ChannelGroup;
}
