service: blogtest

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ap-northeast-2
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
